apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngo-service
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: ngo-secret
      namespace: ns-ngo
      jsonPointers:
        - /data
        - /stringData
  source:
    repoURL: https://github.com/VianaCoder/hackathon-FIAP-solidarytech.git
    targetRevision: main
    path: gitops/services/ngo-service
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-ngo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
