apiVersion: v1
kind: Namespace
metadata:
  name: ns-ngo
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-donation
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-volunteer
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # Allow kube-prometheus-stack to discover ServiceMonitors in this namespace
    prometheus: kube-prometheus
